/**
 * generated by Xtext
 */
package be.kuleuven.learning.simplefsm.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class SfsmDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
