/*
 * generated by Xtext
 */
package be.kuleuven.learning.simplefsm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SfsmUiModule extends be.kuleuven.learning.simplefsm.ui.AbstractSfsmUiModule {
	public SfsmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
