/*
* generated by Xtext
*/
package be.kuleuven.learning.simplefsm;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SfsmUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return be.kuleuven.learning.simplefsm.ui.internal.SfsmActivator.getInstance().getInjector("be.kuleuven.learning.simplefsm.Sfsm");
	}
	
}
