grammar be.kuleuven.learning.simplefsm.Sfsm with org.eclipse.xtext.common.Terminals

//generate sfsm "http://www.kuleuven.be/learning/simplefsm/Sfsm"
import "be.kuleuven.learning.simplefsm"

SimpleFiniteStateMachine:
	'sfsm' name=ID
	'{'
		'initial' states += State
		(states += State)*
	'}'
;

State returns State:
	'state' name=ID
	'{'
		'action' STRING
		(outgoingTransitions += Transition)*
	'}'
;

Transition returns Transition:
	'event' event=STRING  'goto' target=[State|ID]
;