/*
* generated by Xtext
*/
package be.kuleuven.learning.simplefsm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SfsmStandaloneSetup extends SfsmStandaloneSetupGenerated{

	public static void doSetup() {
		new SfsmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

