/*
 * generated by Xtext
 */
package be.kuleuven.learning.simplefsm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SfsmRuntimeModule extends be.kuleuven.learning.simplefsm.AbstractSfsmRuntimeModule {

}
