/*
 * generated by Xtext
 */
package be.kuleuven.learning.simplefsm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import be.kuleuven.learning.simplefsm.ui.internal.SfsmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SfsmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SfsmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SfsmActivator.getInstance().getInjector(SfsmActivator.BE_KULEUVEN_LEARNING_SIMPLEFSM_SFSM);
	}
	
}
