/**
 * generated by Xtext
 */
package be.kuleuven.learning.simplefsm.ui.contentassist;

import be.kuleuven.learning.simplefsm.ui.contentassist.AbstractSfsmProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SfsmProposalProvider extends AbstractSfsmProposalProvider {
}
