/*
* generated by Xtext
*/
package be.kuleuven.learning.simplefsm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SfsmAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("be/kuleuven/learning/simplefsm/parser/antlr/internal/InternalSfsm.tokens");
	}
}
