/**
 * generated by Xtext
 */
package be.kuleuven.learning.simplefsm.validation;

import be.kuleuven.learning.simplefsm.validation.AbstractSfsmValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SfsmValidator extends AbstractSfsmValidator {
}
